#ifndef STAG2000_FUNCS_H
#define STAG2000_FUNCS_H

/* Functions src/stag2000/stag2000.c defines or declares, for the units after it
 * (in the single file the definition was the prototype for later code). */
void Stg20_StaticBgDraw(Actor *a);
void Stg20_StageMain(Actor *a);
s32 Stg20_TestSpecialFlag(s32 id);
void Stg20_SetSpecialFlag(s32 id, s32 on);
s32 Stg20_IsOnCellCenter(Actor *a);
s32 Stg20_AreaSelectFindDir(Actor *a, s32 dir);
void Stg20_AreaSelectUpdate(Actor *a);
void Stg20_AreaSelectDraw(Actor *a);
void Stg20_LabRosterDraw(Actor *a);
void Stg20_LabSkillsUpdate(Actor *a);
void Stg20_BuildMapGrid(Actor *a);
s32 Stg20_GetGridCell(Stg20Cell *c);
void Stg20_MarkGridOccupant(Stg20Cell *c, s32 set, s32 flag);
void Stg20_MapBgInit(Actor *a, s32 v);
void Stg20_MapBgUpdate(Actor *a);
void Stg20_StartBgShake(void);
void Stg20_StaticBgInit(Actor *a, s32 v);
void Stg20_StaticBgUpdate(Actor *a);
void Stg20_LabDnaDigivolve(Actor *a);
void Stg20_LabDigivolve(Actor *a);
void Stg20_DigiLabUpdate(Actor *a);
void Stg20_DigiLabDraw(Actor *a);
void Stg20_ItemShopUpdate(Actor *a);
void Stg20_RefillBeetleHpEp(void);
void Stg20_BeetleShopUpdate(Actor *a);
Stg20MapFile *Stg20_GetMapInfo(void);
void Stg20_ApplyStartPreset(s32 arg0);
s32 Stg20_OwnsDigi(s32 id);
void Stg20_AddBits(s32 d);
void Stg20_RemoveOwnedDigi(s32 id);
void Stg20_OpenText(void *t, s32 text, s32 id, Stg20Cell *pos, s32 color);
Stg20Cell *Stg20_GetActorCell(Actor *a);
void Stg20_SnapToCell(Actor *a, s32 doX, s32 doZ);
void Stg20_SetMoveParams(Actor *a, s32 i);
Stg20Cell *Stg20_GetCellInDir(Actor *a, s32 dir);
s32 Stg20_IsCellBlocked(Actor *a, s32 dir);
void Stg20_AddOccupantMark(Actor *a, Stg20Marks *m, s32 dir, s32 timer);
void Stg20_TickOccupantMarks(Actor *a, Stg20Marks *m);
s32 Stg20_CellDistWeighted(Stg20Cell *c, s32 x, s32 y, s32 flag);
void Stg20_AreaSelectShowName(Actor *a, s32 open);
void Stg20_LabModeSelUpdate(Actor *a);
void Stg20_LabModeSelDraw(Actor *a);
void Stg20_LabRosterSetText(Actor *a, s32 i);
void Stg20_LabRosterFillSlots(Actor *a);
void Stg20_LabRosterUpdate(Actor *a);
void Stg20_MsgWinInit(Actor *a, s32 v);
void Stg20_MsgWinUpdate(Actor *a);
void Stg20_MsgWinDestroy(Actor *a);
void Stg20_MsgWinDraw(Actor *a);
void Stg20_MsgWinClear(void);
void Stg20_MsgWinShowSkillDesc(s32 id);
void Stg20_MsgWinShowSysMsg(s32 id);
void Stg20_MsgWinShowDigiMsg(s32 text, s32 digi);
s32 Stg20_MsgWinGetChoice(void);
void Stg20_LabCaptionUpdate(Actor *a);
void Stg20_LabCaptionDraw(void);
void Stg20_LabInfoDraw(Actor *a);
void Stg20_LabSkillsGroup(Actor *a);
void Stg20_LabSkillsSetText(Actor *a);
void Stg20_LabSkillsDraw(Actor *a);
void Stg20_LabPairUpdate(Actor *a);
void Stg20_LabPairDraw(void);
s32 Stg20_GetDnaTypeIndex(s32 a, s32 b);
u8 Stg20_GetDnaResult(s32 a, s32 b);
void Stg20_ShadowInit(Actor *a, s32 v);
void Stg20_ShadowUpdate(Actor *a);
void Stg20_ShadowDraw(Actor *a);
void Stg20_LabJogBgUpdate(Actor *a);
void Stg20_LabJogBgDraw(Actor *a);
void Stg20_LabDigiModelUpdate(Actor *a);
void Stg20_LabDigiModelDraw(Actor *a);
void Stg20_MapExitUpdate(Actor *a);
Actor *Stg20_FindWalkerByDigiId(s32 id);
void Stg20_WalkerWarpToCell(Actor *a, Stg20Pos2 *pos);
s32 Stg20_WalkerIsPathDone(Actor *a);
void Stg20_WalkerSetAnim(Actor *a, s32 anim);
void Stg20_WalkerInit(Actor *a, Stg20Spawn *s);
void Stg20_WalkerGetInput(Actor *a);
s32 Stg20_InputToDir(Actor *a);
void Stg20_WalkerFaceDir(Actor *a, s32 i);
void Stg20_WalkerHalt(Actor *a);
void Stg20_WalkerUpdate(Actor *a);
void Stg20_WalkerDraw(Actor *a);
void Stg20_XaStreamInit(Actor *a, Stg20Vec3 *v);
void Stg20_XaStreamUpdate(Actor *a);
void Stg20_XaStreamDestroy(Actor *a);
void Stg20_ShopBgUpdate(Actor *a);
void Stg20_ShopBgDraw(Actor *a);
void Stg20_ShopBitsUpdate(Actor *a);
void Stg20_ShopBitsDestroy(Actor *a);
void Stg20_ShopBitsDraw(void);
void Stg20_ItemShopMenuUpdate(Actor *a);
void Stg20_ItemShopMenuDestroy(Actor *a);
void Stg20_ItemShopMenuDraw(Actor *a);
void Stg20_BeetleShopMenuUpdate(Actor *a);

#endif /* STAG2000_FUNCS_H */
