.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_800725B0

dlabel D_800725B0
    /* F250 800725B0 00000E02 */ .word 0x020E0000
    /* F254 800725B4 00000F02 */ .word 0x020F0000
    /* F258 800725B8 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel D_800725B0

nonmatching D_800725BC

dlabel D_800725BC
    /* F25C 800725BC F83E0680 */ .word Stg40_RootInit
    /* F260 800725C0 4C420680 */ .word Stg40_RootUpdate
    /* F264 800725C4 38480680 */ .word Stg40_RootDestroy
    /* F268 800725C8 30480680 */ .word Stg40_RootDraw
    /* F26C 800725CC 14000000 */ .word 0x00000014
    /* F270 800725D0 E0000000 */ .word 0x000000E0
    /* F274 800725D4 A82A0780 */ .word D_80072AA8
    /* F278 800725D8 C02A0780 */ .word D_80072AC0
enddlabel D_800725BC

nonmatching Stg40_LinkedModelTable

dlabel Stg40_LinkedModelTable
    /* F27C 800725DC 7E020000 */ .word 0x0000027E
    /* F280 800725E0 7F020000 */ .word 0x0000027F
    /* F284 800725E4 80020000 */ .word 0x00000280
    /* F288 800725E8 81020000 */ .word 0x00000281
    /* F28C 800725EC 82020000 */ .word 0x00000282
    /* F290 800725F0 83020000 */ .word 0x00000283
    /* F294 800725F4 84020000 */ .word 0x00000284
    /* F298 800725F8 85020000 */ .word 0x00000285
    /* F29C 800725FC 7D020100 */ .word 0x0001027D
    /* F2A0 80072600 7C020100 */ .word 0x0001027C
    /* F2A4 80072604 7B020100 */ .word 0x0001027B
enddlabel Stg40_LinkedModelTable

nonmatching D_80072608

dlabel D_80072608
    /* F2A8 80072608 70490680 */ .word Stg40_LinkedModelInit
    /* F2AC 8007260C 8C490680 */ .word Stg40_LinkedModelUpdate
    /* F2B0 80072610 70110180 */ .word Task_DefaultDestroy
    /* F2B4 80072614 FC4A0680 */ .word Stg40_LinkedModelDraw
    /* F2B8 80072618 2C000000 */ .word 0x0000002C
    /* F2BC 8007261C 00000000 */ .word 0x00000000
enddlabel D_80072608

nonmatching Stg40_FloorPrimIdx

dlabel Stg40_FloorPrimIdx
    /* F2C0 80072620 04020603 */ .word 0x03060204
    /* F2C4 80072624 05000100 */ .word 0x00010005
    /* F2C8 80072628 0B090D0A */ .word 0x0A0D090B
    /* F2CC 8007262C 0C070807 */ .word 0x0708070C
    /* F2D0 80072630 12101411 */ .word 0x11141012
    /* F2D4 80072634 130E0F0E */ .word 0x0E0F0E13
    /* F2D8 80072638 33313532 */ .word 0x32353133
    /* F2DC 8007263C 342F302F */ .word 0x2F302F34
    /* F2E0 80072640 33313532 */ .word 0x32353133
    /* F2E4 80072644 342F302F */ .word 0x2F302F34
    /* F2E8 80072648 3A383C39 */ .word 0x393C383A
    /* F2EC 8007264C 3B363736 */ .word 0x3637363B
    /* F2F0 80072650 16191517 */ .word 0x17151916
    /* F2F4 80072654 183D3E3F */ .word 0x3F3E3D18
    /* F2F8 80072658 */ .short 0x4140
enddlabel Stg40_FloorPrimIdx

nonmatching Stg40_ShadowPrimIdx

dlabel Stg40_ShadowPrimIdx
    /* F2FA 8007265A */ .byte 0x1A
    /* F2FB 8007265B */ .byte 0x00
enddlabel Stg40_ShadowPrimIdx

nonmatching Stg40_WallPrimIdx

dlabel Stg40_WallPrimIdx
    /* F2FC 8007265C 1B1E1C1F */ .word 0x1F1C1E1B
    /* F300 80072660 1D252826 */ .word 0x2628251D
    /* F304 80072664 29272023 */ .word 0x23202729
    /* F308 80072668 2124222A */ .word 0x2A222421
    /* F30C 8007266C 2D2B2E2C */ .word 0x2C2E2B2D
enddlabel Stg40_WallPrimIdx

nonmatching Stg40_WallSides

dlabel Stg40_WallSides
    /* F310 80072670 00080000 */ .word 0x00000800
    /* F314 80072674 00010000 */ .word 0x00000100
    /* F318 80072678 00400004 */ .word 0x04004000
    /* F31C 8007267C 02010100 */ .word 0x00010102
    /* F320 80072680 0100017F */ .word 0x7F010001
    /* F324 80072684 00020400 */ .word 0x00040200
    /* F328 80072688 01000000 */ .word 0x00000001
    /* F32C 8007268C 00400001 */ .word 0x01004000
    /* F330 80072690 06010001 */ .word 0x01000106
    /* F334 80072694 0101007F */ .word 0x7F000101
enddlabel Stg40_WallSides

nonmatching D_80072698

dlabel D_80072698
    /* F338 80072698 18630680 */ .word Stg40_FloorInit
    /* F33C 8007269C E0650680 */ .word Stg40_FloorUpdate
    /* F340 800726A0 70110180 */ .word Task_DefaultDestroy
    /* F344 800726A4 7C660680 */ .word Stg40_FloorDraw
    /* F348 800726A8 A41E0000 */ .word 0x00001EA4
    /* F34C 800726AC 00000000 */ .word 0x00000000
enddlabel D_80072698

nonmatching Stg40_HudLabels

dlabel Stg40_HudLabels
    /* F350 800726B0 76000000 */ .word 0x00000076
    /* F354 800726B4 C4001600 */ .word 0x001600C4
    /* F358 800726B8 77000000 */ .word 0x00000077
    /* F35C 800726BC C4002200 */ .word 0x002200C4
enddlabel Stg40_HudLabels

nonmatching Stg40_HudParts

dlabel Stg40_HudParts
    /* F360 800726C0 0000D407 */ .word 0x07D40000
    /* F364 800726C4 0100D407 */ .word 0x07D40001
enddlabel Stg40_HudParts

nonmatching D_800726C8

dlabel D_800726C8
    /* F368 800726C8 00000000 */ .word 0x00000000
    /* F36C 800726CC 20670680 */ .word Stg40_HudUpdate
    /* F370 800726D0 70110180 */ .word Task_DefaultDestroy
    /* F374 800726D4 D06A0680 */ .word Stg40_HudDraw
    /* F378 800726D8 18000000 */ .word 0x00000018
    /* F37C 800726DC 04000000 */ .word 0x00000004
enddlabel D_800726C8

nonmatching Stg40_BitsLabelText

dlabel Stg40_BitsLabelText
    /* F380 800726E0 80000000 */ .word 0x00000080
    /* F384 800726E4 C4003A00 */ .word 0x003A00C4
enddlabel Stg40_BitsLabelText

nonmatching D_800726E8

dlabel D_800726E8
    /* F388 800726E8 00000000 */ .word 0x00000000
    /* F38C 800726EC E46B0680 */ .word Stg40_BitsWinUpdate
    /* F390 800726F0 70110180 */ .word Task_DefaultDestroy
    /* F394 800726F4 786D0680 */ .word Stg40_BitsWinDraw
    /* F398 800726F8 0C000000 */ .word 0x0000000C
    /* F39C 800726FC 00000000 */ .word 0x00000000
enddlabel D_800726E8

nonmatching Stg40_ItemMenuParts

dlabel Stg40_ItemMenuParts
    /* F3A0 80072700 0300D407 */ .word 0x07D40003
    /* F3A4 80072704 0700D407 */ .word 0x07D40007
enddlabel Stg40_ItemMenuParts

nonmatching D_80072708

dlabel D_80072708
    /* F3A8 80072708 306E0680 */ .word Stg40_ItemMenuInit
    /* F3AC 8007270C 486E0680 */ .word Stg40_ItemMenuUpdate
    /* F3B0 80072710 70110180 */ .word Task_DefaultDestroy
    /* F3B4 80072714 44700680 */ .word Stg40_ItemMenuDraw
    /* F3B8 80072718 48000000 */ .word 0x00000048
    /* F3BC 8007271C 00000000 */ .word 0x00000000
enddlabel D_80072708

nonmatching Stg40_EnemyInfoTextPos

dlabel Stg40_EnemyInfoTextPos
    /* F3C0 80072720 0F00C500 */ .word 0x00C5000F
    /* F3C4 80072724 0F00B600 */ .word 0x00B6000F
    /* F3C8 80072728 3700C500 */ .word 0x00C50037
    /* F3CC 8007272C 0F00D100 */ .word 0x00D1000F
    /* F3D0 80072730 7300C500 */ .word 0x00C50073
    /* F3D4 80072734 7300B600 */ .word 0x00B60073
    /* F3D8 80072738 9B00C500 */ .word 0x00C5009B
    /* F3DC 8007273C 7300D100 */ .word 0x00D10073
    /* F3E0 80072740 D700C500 */ .word 0x00C500D7
    /* F3E4 80072744 D700B600 */ .word 0x00B600D7
    /* F3E8 80072748 FF00C500 */ .word 0x00C500FF
    /* F3EC 8007274C D700D100 */ .word 0x00D100D7
enddlabel Stg40_EnemyInfoTextPos

nonmatching Stg40_EnemyInfoParts

dlabel Stg40_EnemyInfoParts
    /* F3F0 80072750 0400D407 */ .word 0x07D40004
    /* F3F4 80072754 0500D407 */ .word 0x07D40005
    /* F3F8 80072758 0600D407 */ .word 0x07D40006
enddlabel Stg40_EnemyInfoParts

nonmatching D_8007275C

dlabel D_8007275C
    /* F3FC 8007275C E8710680 */ .word Stg40_EnemyInfoInit
    /* F400 80072760 F0710680 */ .word Stg40_EnemyInfoUpdate
    /* F404 80072764 70110180 */ .word Task_DefaultDestroy
    /* F408 80072768 54740680 */ .word Stg40_EnemyInfoDraw
    /* F40C 8007276C 38000000 */ .word 0x00000038
    /* F410 80072770 00000000 */ .word 0x00000000
enddlabel D_8007275C

nonmatching D_80072774

dlabel D_80072774
    /* F414 80072774 84770680 */ .word Stg40_MsgWinInit
    /* F418 80072778 8C770680 */ .word Stg40_MsgWinUpdate
    /* F41C 8007277C 70110180 */ .word Task_DefaultDestroy
    /* F420 80072780 F4770680 */ .word Stg40_MsgWinDraw
    /* F424 80072784 28000000 */ .word 0x00000028
    /* F428 80072788 00000000 */ .word 0x00000000
enddlabel D_80072774

nonmatching Stg40_FlashPattern

dlabel Stg40_FlashPattern
    /* F42C 8007278C 01010001 */ .word 0x01000101
    /* F430 80072790 00010000 */ .word 0x00000100
    /* F434 80072794 01000000 */ .word 0x00000001
    /* F438 80072798 0100FF00 */ .word 0x00FF0001
enddlabel Stg40_FlashPattern

nonmatching Stg40_FlashColors

dlabel Stg40_FlashColors
    /* F43C 8007279C FFFFFF00 */ .word 0x00FFFFFF
    /* F440 800727A0 FF000000 */ .word 0x000000FF
    /* F444 800727A4 FF00FF00 */ .word 0x00FF00FF
enddlabel Stg40_FlashColors

nonmatching D_800727A8

dlabel D_800727A8
    /* F448 800727A8 807A0680 */ .word Stg40_ObjInit
    /* F44C 800727AC A87B0680 */ .word Stg40_ObjUpdate
    /* F450 800727B0 70110180 */ .word Task_DefaultDestroy
    /* F454 800727B4 B47D0680 */ .word Stg40_ObjDraw
    /* F458 800727B8 3C000000 */ .word 0x0000003C
    /* F45C 800727BC 04000000 */ .word 0x00000004
enddlabel D_800727A8

nonmatching Stg40_DirOffsets

dlabel Stg40_DirOffsets
    /* F460 800727C0 01000100 */ .word 0x00010001
    /* F464 800727C4 00000100 */ .word 0x00010000
    /* F468 800727C8 FFFF0100 */ .word 0x0001FFFF
    /* F46C 800727CC FFFF0000 */ .word 0x0000FFFF
    /* F470 800727D0 FFFFFFFF */ .word 0xFFFFFFFF
    /* F474 800727D4 0000FFFF */ .word 0xFFFF0000
    /* F478 800727D8 0100FFFF */ .word 0xFFFF0001
    /* F47C 800727DC 01000000 */ .word 0x00000001
    /* F480 800727E0 01000100 */ .word 0x00010001
    /* F484 800727E4 00000100 */ .word 0x00010000
enddlabel Stg40_DirOffsets

nonmatching Stg40_ObstacleItemReqs

dlabel Stg40_ObstacleItemReqs
    /* F488 800727E8 0B001700 */ .word 0x0017000B
    /* F48C 800727EC 2100FFFF */ .word 0xFFFF0021
    /* F490 800727F0 FFFF0000 */ .word 0x0000FFFF
    /* F494 800727F4 2400FD01 */ .word 0x01FD0024
    /* F498 800727F8 0B002000 */ .word 0x0020000B
    /* F49C 800727FC 2100FFFF */ .word 0xFFFF0021
    /* F4A0 80072800 FFFF0000 */ .word 0x0000FFFF
    /* F4A4 80072804 2400FD01 */ .word 0x01FD0024
    /* F4A8 80072808 0000FFFF */ .word 0xFFFF0000
    /* F4AC 8007280C FFFFFFFF */ .word 0xFFFFFFFF
    /* F4B0 80072810 FFFF0000 */ .word 0x0000FFFF
    /* F4B4 80072814 00000000 */ .word 0x00000000
    /* F4B8 80072818 0C001800 */ .word 0x0018000C
    /* F4BC 8007281C 2800FFFF */ .word 0xFFFF0028
    /* F4C0 80072820 FFFF0000 */ .word 0x0000FFFF
    /* F4C4 80072824 3D00FD01 */ .word 0x01FD003D
    /* F4C8 80072828 0C002500 */ .word 0x0025000C
    /* F4CC 8007282C 2800FFFF */ .word 0xFFFF0028
    /* F4D0 80072830 FFFF0000 */ .word 0x0000FFFF
    /* F4D4 80072834 3D00FD01 */ .word 0x01FD003D
    /* F4D8 80072838 0C002600 */ .word 0x0026000C
    /* F4DC 8007283C 2800FFFF */ .word 0xFFFF0028
    /* F4E0 80072840 FFFF0000 */ .word 0x0000FFFF
    /* F4E4 80072844 3D00FD01 */ .word 0x01FD003D
    /* F4E8 80072848 0C002700 */ .word 0x0027000C
    /* F4EC 8007284C 2800FFFF */ .word 0xFFFF0028
    /* F4F0 80072850 FFFF0000 */ .word 0x0000FFFF
    /* F4F4 80072854 3D00FD01 */ .word 0x01FD003D
enddlabel Stg40_ObstacleItemReqs

nonmatching Stg40_GiftGunReq

dlabel Stg40_GiftGunReq
    /* F4F8 80072858 08002200 */ .word 0x00220008
    /* F4FC 8007285C 23002400 */ .word 0x00240023
    /* F500 80072860 1B000000 */ .word 0x0000001B
    /* F504 80072864 5100FD01 */ .word 0x01FD0051
enddlabel Stg40_GiftGunReq

nonmatching Stg40_StatusMsgIds

dlabel Stg40_StatusMsgIds
    /* F508 80072868 1E00FD01 */ .word 0x01FD001E
    /* F50C 8007286C 1C00FD01 */ .word 0x01FD001C
    /* F510 80072870 2F00FD01 */ .word 0x01FD002F
    /* F514 80072874 3000FD01 */ .word 0x01FD0030
    /* F518 80072878 3100FD01 */ .word 0x01FD0031
    /* F51C 8007287C 3200FD01 */ .word 0x01FD0032
    /* F520 80072880 3300FD01 */ .word 0x01FD0033
    /* F524 80072884 3400FD01 */ .word 0x01FD0034
enddlabel Stg40_StatusMsgIds

.align 2
nonmatching Stg40_GiftTakeChance

dlabel Stg40_GiftTakeChance
    /* F528 80072888 */ .asciz "`\\XTPLHD@"
    /* 605C5854504C484440000000 */
.align 2
enddlabel Stg40_GiftTakeChance

nonmatching Stg40_GiftPointsByLevel

dlabel Stg40_GiftPointsByLevel
    /* F534 80072894 0A142850 */ .word 0x5028140A
    /* F538 80072898 A0000000 */ .word 0x000000A0
enddlabel Stg40_GiftPointsByLevel

nonmatching Stg40_ShootMsgIds

dlabel Stg40_ShootMsgIds
    /* F53C 8007289C 2000FD01 */ .word 0x01FD0020
    /* F540 800728A0 2100FD01 */ .word 0x01FD0021
    /* F544 800728A4 2200FD01 */ .word 0x01FD0022
    /* F548 800728A8 2300FD01 */ .word 0x01FD0023
    /* F54C 800728AC 00000000 */ .word 0x00000000
    /* F550 800728B0 00000000 */ .word 0x00000000
    /* F554 800728B4 3500FD01 */ .word 0x01FD0035
    /* F558 800728B8 3900FD01 */ .word 0x01FD0039
    /* F55C 800728BC 3600FD01 */ .word 0x01FD0036
    /* F560 800728C0 3A00FD01 */ .word 0x01FD003A
    /* F564 800728C4 3700FD01 */ .word 0x01FD0037
    /* F568 800728C8 3B00FD01 */ .word 0x01FD003B
    /* F56C 800728CC 3800FD01 */ .word 0x01FD0038
    /* F570 800728D0 3C00FD01 */ .word 0x01FD003C
enddlabel Stg40_ShootMsgIds

nonmatching Stg40_PadDirTable

dlabel Stg40_PadDirTable
    /* F574 800728D4 FFFF0000 */ .word 0x0000FFFF
    /* F578 800728D8 0400FFFF */ .word 0xFFFF0004
    /* F57C 800728DC 06000700 */ .word 0x00070006
    /* F580 800728E0 0500FFFF */ .word 0xFFFF0005
    /* F584 800728E4 02000100 */ .word 0x00010002
    /* F588 800728E8 0300FFFF */ .word 0xFFFF0003
    /* F58C 800728EC FFFFFFFF */ .word 0xFFFFFFFF
    /* F590 800728F0 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel Stg40_PadDirTable

nonmatching Stg40_EnemyAiTable

dlabel Stg40_EnemyAiTable
    /* F594 800728F4 02000201 */ .word 0x01020002
    /* F598 800728F8 04020302 */ .word 0x02030204
    /* F59C 800728FC 07020602 */ .word 0x02060207
    /* F5A0 80072900 05020203 */ .word 0x03020205
enddlabel Stg40_EnemyAiTable

nonmatching Stg40_EnemyPaceTable

dlabel Stg40_EnemyPaceTable
    /* F5A4 80072904 01000200 */ .word 0x00020001
    /* F5A8 80072908 00010100 */ .word 0x00010100
enddlabel Stg40_EnemyPaceTable

nonmatching Stg40_TaskDescs

dlabel Stg40_TaskDescs
    /* F5AC 8007290C BC250780 */ .word D_800725BC
    /* F5B0 80072910 00000000 */ .word 0x00000000
    /* F5B4 80072914 98260780 */ .word D_80072698
    /* F5B8 80072918 842A0780 */ .word D_80072A84
    /* F5BC 8007291C A8270780 */ .word D_800727A8
    /* F5C0 80072920 00000000 */ .word 0x00000000
    /* F5C4 80072924 88290780 */ .word D_80072988
    /* F5C8 80072928 08260780 */ .word D_80072608
    /* F5CC 8007292C 74270780 */ .word D_80072774
    /* F5D0 80072930 C8260780 */ .word D_800726C8
    /* F5D4 80072934 E8260780 */ .word D_800726E8
    /* F5D8 80072938 08270780 */ .word D_80072708
    /* F5DC 8007293C 5C270780 */ .word D_8007275C
    /* F5E0 80072940 C8260780 */ .word D_800726C8
enddlabel Stg40_TaskDescs

nonmatching D_80072944

dlabel D_80072944
    /* F5E4 80072944 00000000 */ .word 0x00000000
enddlabel D_80072944

nonmatching Stg40_AutomapClut

dlabel Stg40_AutomapClut
    /* F5E8 80072948 009CE08C */ .word 0x8CE09C00
    /* F5EC 8007294C 0080E79C */ .word 0x9CE78000
    /* F5F0 80072950 E79CE79C */ .word 0x9CE79CE7
    /* F5F4 80072954 E79CE79C */ .word 0x9CE79CE7
    /* F5F8 80072958 E79CE79C */ .word 0x9CE79CE7
    /* F5FC 8007295C FFFFFFFF */ .word 0xFFFFFFFF
    /* F600 80072960 FFFFFFFF */ .word 0xFFFFFFFF
    /* F604 80072964 FFFFFFFF */ .word 0xFFFFFFFF
    /* F608 80072968 00804AA9 */ .word 0xA94A8000
    /* F60C 8007296C 0080E79C */ .word 0x9CE78000
    /* F610 80072970 E79CE79C */ .word 0x9CE79CE7
    /* F614 80072974 E79CE79C */ .word 0x9CE79CE7
    /* F618 80072978 E79CE79C */ .word 0x9CE79CE7
    /* F61C 8007297C 18E318E3 */ .word 0xE318E318
    /* F620 80072980 18E318E3 */ .word 0xE318E318
    /* F624 80072984 18E318E3 */ .word 0xE318E318
enddlabel Stg40_AutomapClut

nonmatching D_80072988

dlabel D_80072988
    /* F628 80072988 ACFD0680 */ .word Stg40_AutomapInit
    /* F62C 8007298C B4FD0680 */ .word Stg40_AutomapUpdate
    /* F630 80072990 5CFE0680 */ .word Stg40_AutomapDestroy
    /* F634 80072994 90FE0680 */ .word Stg40_AutomapDraw
    /* F638 80072998 700B0000 */ .word 0x00000B70
    /* F63C 8007299C 04000000 */ .word 0x00000004
enddlabel D_80072988

nonmatching Stg40_FloorBitsPal

dlabel Stg40_FloorBitsPal
    /* F640 800729A0 02000100 */ .word 0x00010002
    /* F644 800729A4 04000300 */ .word 0x00030004
    /* F648 800729A8 07000600 */ .word 0x00060007
    /* F64C 800729AC 05000000 */ .word 0x00000005
    /* F650 800729B0 00000000 */ .word 0x00000000
enddlabel Stg40_FloorBitsPal

nonmatching Stg40_SpecialFloorValues

dlabel Stg40_SpecialFloorValues
    /* F654 800729B4 04000300 */ .word 0x00030004
    /* F658 800729B8 07000600 */ .word 0x00060007
    /* F65C 800729BC 05000200 */ .word 0x00020005
enddlabel Stg40_SpecialFloorValues

nonmatching Stg40_FillNeighbours

dlabel Stg40_FillNeighbours
    /* F660 800729C0 00000000 */ .word 0x00000000
    /* F664 800729C4 FFFFFFFF */ .word 0xFFFFFFFF
    /* F668 800729C8 00000000 */ .word 0x00000000
    /* F66C 800729CC 01000000 */ .word 0x00000001
    /* F670 800729D0 FFFFFFFF */ .word 0xFFFFFFFF
    /* F674 800729D4 00000000 */ .word 0x00000000
    /* F678 800729D8 01000000 */ .word 0x00000001
    /* F67C 800729DC 00000000 */ .word 0x00000000
enddlabel Stg40_FillNeighbours

nonmatching Stg40_TrapPartSlots

dlabel Stg40_TrapPartSlots
    /* F680 800729E0 0D000E00 */ .word 0x000E000D
    /* F684 800729E4 0B000C00 */ .word 0x000C000B
    /* F688 800729E8 08000A00 */ .word 0x000A0008
    /* F68C 800729EC 09001100 */ .word 0x00110009
    /* F690 800729F0 12000500 */ .word 0x00050012
    /* F694 800729F4 06000F00 */ .word 0x000F0006
enddlabel Stg40_TrapPartSlots

nonmatching Stg40_TrapDisarmRanks

dlabel Stg40_TrapDisarmRanks
    /* F698 800729F8 04040404 */ .word 0x04040404
    /* F69C 800729FC 04040001 */ .word 0x01000404
    /* F6A0 80072A00 02030404 */ .word 0x04040302
    /* F6A4 80072A04 00000102 */ .word 0x02010000
    /* F6A8 80072A08 03040000 */ .word 0x00000403
    /* F6AC 80072A0C 00010203 */ .word 0x03020100
    /* F6B0 80072A10 00000000 */ .word 0x00000000
    /* F6B4 80072A14 01020000 */ .word 0x00000201
    /* F6B8 80072A18 00000001 */ .word 0x01000000
enddlabel Stg40_TrapDisarmRanks

.align 2
nonmatching Stg40_TrapDisarmChance

dlabel Stg40_TrapDisarmChance
    /* F6BC 80072A1C */ .asciz "d"
    /* 64000000 */
.align 2
.align 2
    /* F6C0 80072A20 */ .asciz "P"
    /* 50000000 */
.align 2
.align 2
    /* F6C4 80072A24 */ .asciz "2"
    /* 32000000 */
.align 2
    /* F6C8 80072A28 19000000 */ .word 0x00000019
    /* F6CC 80072A2C 00000000 */ .word 0x00000000
enddlabel Stg40_TrapDisarmChance

nonmatching Stg40_TrapEffectTable

dlabel Stg40_TrapEffectTable
    /* F6D0 80072A30 00000001 */ .word 0x01000000
    /* F6D4 80072A34 01010202 */ .word 0x02020101
    /* F6D8 80072A38 02030303 */ .word 0x03030302
    /* F6DC 80072A3C 04050607 */ .word 0x07060504
    /* F6E0 80072A40 08090A0B */ .word 0x0B0A0908
    /* F6E4 80072A44 0C0D0E0F */ .word 0x0F0E0D0C
    /* F6E8 80072A48 10000000 */ .word 0x00000010
enddlabel Stg40_TrapEffectTable

nonmatching Stg40_RandomPartSlots

dlabel Stg40_RandomPartSlots
    /* F6EC 80072A4C 05060809 */ .word 0x09080605
    /* F6F0 80072A50 0A0B0C0D */ .word 0x0D0C0B0A
    /* F6F4 80072A54 0E0F1112 */ .word 0x12110F0E
enddlabel Stg40_RandomPartSlots

nonmatching Stg40_HazardRevealChance

dlabel Stg40_HazardRevealChance
    /* F6F8 80072A58 00000000 */ .word 0x00000000
    /* F6FC 80072A5C 00503200 */ .word 0x00325000
    /* F700 80072A60 00006450 */ .word 0x50640000
    /* F704 80072A64 32000064 */ .word 0x64000032
    /* F708 80072A68 64503200 */ .word 0x00325064
    /* F70C 80072A6C 64646450 */ .word 0x50646464
    /* F710 80072A70 32646464 */ .word 0x64646432
    /* F714 80072A74 64500000 */ .word 0x00005064
enddlabel Stg40_HazardRevealChance

nonmatching Stg40_BugNestRevealChance

dlabel Stg40_BugNestRevealChance
    /* F718 80072A78 00000050 */ .word 0x50000000
    /* F71C 80072A7C 32006450 */ .word 0x50640032
    /* F720 80072A80 32646450 */ .word 0x50646432
enddlabel Stg40_BugNestRevealChance

nonmatching D_80072A84

dlabel D_80072A84
    /* F724 80072A84 18240780 */ .word Stg40_CameraInit
    /* F728 80072A88 68240780 */ .word Stg40_CameraUpdate
    /* F72C 80072A8C 70110180 */ .word Task_DefaultDestroy
    /* F730 80072A90 A8250780 */ .word Stg40_CameraDraw
    /* F734 80072A94 74020000 */ .word 0x00000274
    /* F738 80072A98 00000000 */ .word 0x00000000
    /* F73C 80072A9C 00000000 */ .word 0x00000000
enddlabel D_80072A84

nonmatching Stg40_RootTask

dlabel Stg40_RootTask
    /* F740 80072AA0 00000000 */ .word 0x00000000
enddlabel Stg40_RootTask

nonmatching Stg40_RootChildren

dlabel Stg40_RootChildren
    /* F744 80072AA4 00000000 */ .word 0x00000000
enddlabel Stg40_RootChildren

nonmatching D_80072AA8

dlabel D_80072AA8
    /* F748 80072AA8 00000000 */ .word 0x00000000
    /* F74C 80072AAC 00000000 */ .word 0x00000000
    /* F750 80072AB0 00000000 */ .word 0x00000000
    /* F754 80072AB4 00000000 */ .word 0x00000000
    /* F758 80072AB8 00000000 */ .word 0x00000000
    /* F75C 80072ABC 00000000 */ .word 0x00000000
enddlabel D_80072AA8

nonmatching D_80072AC0

dlabel D_80072AC0
    /* F760 80072AC0 00000000 */ .word 0x00000000
    /* F764 80072AC4 00000000 */ .word 0x00000000
    /* F768 80072AC8 00000000 */ .word 0x00000000
    /* F76C 80072ACC 00000000 */ .word 0x00000000
    /* F770 80072AD0 00000000 */ .word 0x00000000
    /* F774 80072AD4 00000000 */ .word 0x00000000
    /* F778 80072AD8 00000000 */ .word 0x00000000
    /* F77C 80072ADC 00000000 */ .word 0x00000000
    /* F780 80072AE0 00000000 */ .word 0x00000000
    /* F784 80072AE4 00000000 */ .word 0x00000000
    /* F788 80072AE8 00000000 */ .word 0x00000000
    /* F78C 80072AEC 00000000 */ .word 0x00000000
    /* F790 80072AF0 00000000 */ .word 0x00000000
    /* F794 80072AF4 00000000 */ .word 0x00000000
    /* F798 80072AF8 00000000 */ .word 0x00000000
    /* F79C 80072AFC 00000000 */ .word 0x00000000
    /* F7A0 80072B00 00000000 */ .word 0x00000000
    /* F7A4 80072B04 00000000 */ .word 0x00000000
    /* F7A8 80072B08 00000000 */ .word 0x00000000
    /* F7AC 80072B0C 00000000 */ .word 0x00000000
    /* F7B0 80072B10 00000000 */ .word 0x00000000
    /* F7B4 80072B14 00000000 */ .word 0x00000000
    /* F7B8 80072B18 00000000 */ .word 0x00000000
    /* F7BC 80072B1C 00000000 */ .word 0x00000000
    /* F7C0 80072B20 00000000 */ .word 0x00000000
    /* F7C4 80072B24 00000000 */ .word 0x00000000
    /* F7C8 80072B28 00000000 */ .word 0x00000000
    /* F7CC 80072B2C 00000000 */ .word 0x00000000
    /* F7D0 80072B30 00000000 */ .word 0x00000000
    /* F7D4 80072B34 00000000 */ .word 0x00000000
    /* F7D8 80072B38 00000000 */ .word 0x00000000
    /* F7DC 80072B3C 00000000 */ .word 0x00000000
    /* F7E0 80072B40 00000000 */ .word 0x00000000
    /* F7E4 80072B44 00000000 */ .word 0x00000000
    /* F7E8 80072B48 00000000 */ .word 0x00000000
    /* F7EC 80072B4C 00000000 */ .word 0x00000000
    /* F7F0 80072B50 00000000 */ .word 0x00000000
    /* F7F4 80072B54 00000000 */ .word 0x00000000
    /* F7F8 80072B58 00000000 */ .word 0x00000000
    /* F7FC 80072B5C 00000000 */ .word 0x00000000
enddlabel D_80072AC0

nonmatching Stg40_RootState

dlabel Stg40_RootState
    /* F800 80072B60 00000000 */ .word 0x00000000
    /* F804 80072B64 00000000 */ .word 0x00000000
enddlabel Stg40_RootState

nonmatching Stg40_FloorTask

dlabel Stg40_FloorTask
    /* F808 80072B68 00000000 */ .word 0x00000000
enddlabel Stg40_FloorTask

nonmatching Stg40_FloorWork

dlabel Stg40_FloorWork
    /* F80C 80072B6C 00000000 */ .word 0x00000000
enddlabel Stg40_FloorWork

nonmatching Stg40_ItemMenuTask

dlabel Stg40_ItemMenuTask
    /* F810 80072B70 00000000 */ .word 0x00000000
    /* F814 80072B74 00000000 */ .word 0x00000000
enddlabel Stg40_ItemMenuTask

nonmatching Stg40_EnemyInfoTask

dlabel Stg40_EnemyInfoTask
    /* F818 80072B78 00000000 */ .word 0x00000000
    /* F81C 80072B7C 00000000 */ .word 0x00000000
enddlabel Stg40_EnemyInfoTask

nonmatching Stg40_MsgWinTask

dlabel Stg40_MsgWinTask
    /* F820 80072B80 00000000 */ .word 0x00000000
enddlabel Stg40_MsgWinTask

nonmatching Stg40_MsgWinTexts

dlabel Stg40_MsgWinTexts
    /* F824 80072B84 00000000 */ .word 0x00000000
    /* F828 80072B88 00000000 */ .word 0x00000000
    /* F82C 80072B8C 00000000 */ .word 0x00000000
enddlabel Stg40_MsgWinTexts

nonmatching Stg40_DigitBufs

dlabel Stg40_DigitBufs
    /* F830 80072B90 00000000 */ .word 0x00000000
    /* F834 80072B94 00000000 */ .word 0x00000000
    /* F838 80072B98 00000000 */ .word 0x00000000
    /* F83C 80072B9C 00000000 */ .word 0x00000000
    /* F840 80072BA0 00000000 */ .word 0x00000000
    /* F844 80072BA4 00000000 */ .word 0x00000000
    /* F848 80072BA8 00000000 */ .word 0x00000000
    /* F84C 80072BAC 00000000 */ .word 0x00000000
enddlabel Stg40_DigitBufs

nonmatching Stg40_AutomapWork

dlabel Stg40_AutomapWork
    /* F850 80072BB0 00000000 */ .word 0x00000000
    /* F854 80072BB4 00000000 */ .word 0x00000000
enddlabel Stg40_AutomapWork

nonmatching D_80072BB8

dlabel D_80072BB8
    /* F858 80072BB8 00000000 */ .word 0x00000000
    /* F85C 80072BBC 00000000 */ .word 0x00000000
enddlabel D_80072BB8

nonmatching Stg40_CameraTask

dlabel Stg40_CameraTask
    /* F860 80072BC0 00000000 */ .word 0x00000000
enddlabel Stg40_CameraTask
