#!/usr/bin/env python3
"""Compile the GLSL shaders of the GPU renderer (backend/shaders/*.vert, *.frag) to SPIR-V with
glslang and write them as C arrays into backend/psxgpu_hw_spv.h. The header is committed, so a
normal build needs no shader compiler; run this after a shader change.

    venv/Scripts/python.exe tools/build_shaders.py

glslang: DW2_GLSLANG = the glslang executable (default D:/tools/glslang/bin/glslang.exe on
Windows, glslang in PATH elsewhere)."""

import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "backend", "shaders")
OUT = os.path.join(ROOT, "backend", "psxgpu_hw_spv.h")


def main():
    default = "D:/tools/glslang/bin/glslang.exe" if os.name == "nt" else (shutil.which("glslang") or "glslang")
    glslang = os.environ.get("DW2_GLSLANG", default)
    names = sorted(n for n in os.listdir(SHADERS) if n.endswith((".vert", ".frag")))
    lines = ["/* Generated by tools/build_shaders.py from backend/shaders/ (SPIR-V, glslang). Do not edit. */",
             "#ifndef BACKEND_PSXGPU_HW_SPV_H", "#define BACKEND_PSXGPU_HW_SPV_H", "", "#include <stdint.h>", ""]
    with tempfile.TemporaryDirectory() as tmp:
        for name in names:
            spv = os.path.join(tmp, name + ".spv")
            cmd = [glslang, "-V", "--target-env", "vulkan1.0", "-o", spv, os.path.join(SHADERS, name)]
            if subprocess.call(cmd, stdout=subprocess.DEVNULL) != 0:
                subprocess.call(cmd)
                sys.exit("SHADER FAILED: %s" % name)
            data = open(spv, "rb").read()
            words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
            ident = "spv_" + name.replace(".", "_")
            lines.append("static const uint32_t %s[%d] = {" % (ident, len(words)))
            for i in range(0, len(words), 8):
                lines.append("    " + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",")
            lines.append("};")
            lines.append("")
    lines.append("#endif /* BACKEND_PSXGPU_HW_SPV_H */")
    text = "\n".join(lines) + "\n"
    if not os.path.exists(OUT) or open(OUT).read() != text:
        with open(OUT, "w", newline="\n") as f:
            f.write(text)
        print("written %s" % os.path.relpath(OUT, ROOT).replace("\\", "/"))
    else:
        print("unchanged %s" % os.path.relpath(OUT, ROOT).replace("\\", "/"))


if __name__ == "__main__":
    main()
