#!/usr/bin/env python3
"""Who owns each .rodata item of a unit (issue #5 E2.2).

Reads the unit's splat rodata file (asm/USA/<unit>/data/*.rodata.s), splits it into
items (one per dlabel, with the .align lines in front of it) and gives every item an
owner: the lowest-address function whose retail asm references it. Items nobody
references stay with the previous item's owner. The owner's state in src/ (natural C
or INCLUDE_ASM) decides how the item gets into the C object:

  jtbl of a natural function   cc1 emits it after the function
  anything else                INCLUDE_RODATA in front of the owner

Usage:
    python3 tools/rodata_own.py UNIT            report owners and order problems
    python3 tools/rodata_own.py UNIT --json     machine-readable plan
"""
import glob
import json
import os
import re
import sys

ITEM = re.compile(r"(?ms)^dlabel (\w+)\n.*?^enddlabel \1\n")


def rodata_file(unit):
    fs = glob.glob("asm/USA/%s/data/*.rodata.s" % unit)
    return fs[0] if fs else None


def items_of(path):
    """[(name, addr, text)] in file order; text runs from the end of the previous item
    (so .align / nonmatching lines go with the item they precede)."""
    t = open(path, encoding="utf-8").read()
    out, last = [], None
    head = t.index('/* Generated by spimdisasm')
    head = t.index("\n", head) + 1
    prev = head
    for m in ITEM.finditer(t):
        a = re.search(r"/\* \w+ ([0-9A-F]{8}) ", m.group(0))
        out.append([m.group(1), int(a.group(1), 16), t[prev:m.end()]])
        prev = m.end()
    if out:
        out[-1][2] += t[prev:]
    return out


def funcs_of(unit):
    """{name: (addr, path)} for every function .s of the unit."""
    fs = {}
    for p in glob.glob("asm/USA/%s/nonmatchings/**/*.s" % unit, recursive=True):
        t = open(p, encoding="utf-8", errors="replace").read()
        m = re.search(r"/\* \w+ ([0-9A-F]{8}) [0-9A-F]{8} \*/", t)
        if m:
            fs[os.path.basename(p)[:-2]] = (int(m.group(1), 16), p, t)
    return fs


def c_state(unit):
    """{fn: ('c'|'asm', file)} from src/<unit>/*.c."""
    st = {}
    for f in glob.glob("src/%s/*.c" % unit):
        t = open(f, encoding="latin-1").read()
        asm = set(re.findall(r'INCLUDE_ASM\("[^"]*", (\w+)\);', t))
        nm = set(re.findall(r"(?ms)#ifdef NORMALIZED\n.*?#else\nINCLUDE_ASM\(\"[^\"]*\", (\w+)\);", t))
        for fn in asm:
            st[fn] = ("asm", f)
        for m in re.finditer(r"(?m)^[A-Za-z_][^;{}()\n]*\b(\w+)\s*\([^;{}]*\)\s*(?:[^;{}()]*;\s*)*\{", t):
            fn = m.group(1)
            if fn not in st:
                st[fn] = ("c", f)
        for fn in nm:
            st[fn] = ("asm", f)
    return st


# Items whose first user is not their unit: D_80010000 (overlay load address, read by
# Ovl_Load) sits before the 187C tables, which only line up (8-aligned jump tables) when
# 187C's .rodata starts after it, so it belongs to the unit before, 156C.
OWNER_OVERRIDE = {"main": {"D_80010000": "func_80010D74"}}


def plan(unit):
    rf = rodata_file(unit)
    items = items_of(rf)
    fs = funcs_of(unit)
    st = c_state(unit)
    owner = {}
    for name, addr, _t in items:
        pat = re.compile(r"\b%s\b" % re.escape(name))
        refs = sorted((a, fn) for fn, (a, _p, t) in fs.items() if pat.search(t))
        owner[name] = refs[0][1] if refs else None
    owner.update(OWNER_OVERRIDE.get(unit, {}))
    rows, cur = [], None
    for name, addr, text in items:
        o = owner[name] or cur
        cur = o
        kind = "jtbl" if name.startswith("jtbl_") else "data"
        how = None
        if o is None:
            how = "orphan"
        else:
            s = st.get(o, (None, None))[0]
            if s is None:
                how = "unknown-owner"
            elif kind == "jtbl" and s == "c":
                how = "cc1"
            else:
                how = "include"
        rows.append(dict(name=name, addr=addr, kind=kind, owner=o, how=how,
                         owner_addr=fs[o][0] if o in fs else None,
                         file=st.get(o, (None, None))[1]))
    # order check: owners must be non-decreasing by address, and for a natural owner
    # the include items must all come before its cc1 tables
    probs = []
    last = -1
    for r in rows:
        if r["owner_addr"] is not None:
            if r["owner_addr"] < last:
                probs.append("order: %s (owner %s) after a later owner" % (r["name"], r["owner"]))
            last = max(last, r["owner_addr"])
    seen_cc1 = set()
    for r in rows:
        if r["how"] == "cc1":
            seen_cc1.add(r["owner"])
        elif r["how"] == "include" and r["owner"] in seen_cc1 and st.get(r["owner"], ("",))[0] == "c":
            probs.append("after-table: %s follows a cc1 table of %s" % (r["name"], r["owner"]))
    return rows, probs


def split(unit):
    """Write every item of the unit's rodata file to asm/USA/<unit>/rodata/<name>.s
    (the INCLUDE_RODATA targets). Returns the item names."""
    out = "asm/USA/%s/rodata" % unit
    os.makedirs(out, exist_ok=True)
    names = []
    for name, _addr, text in items_of(rodata_file(unit)):
        # spimdisasm's `.align 3` lines are guesses relative to the old single rodata
        # file (padding is in the words); word alignment (strings) stays. A jump table
        # keeps cc1's own `.align 3`, applied relative to the unit's .rodata start.
        text = re.sub(r"(?m)^\.align 3\n", "", text)
        if name.startswith("jtbl_"):
            text = ".align 3\n" + text
        p = os.path.join(out, name + ".s")
        if not os.path.exists(p) or open(p, encoding="utf-8").read() != text:
            open(p, "w", encoding="utf-8", newline="\n").write(text)
        names.append(name)
    return names


def _def_span(text, fn):
    """(start, end) line offsets of fn's block in a C file: the #ifdef NORMALIZED ..
    #endif wrapper, a bare INCLUDE_ASM line, or the C definition through its brace."""
    m = re.search(r'(?ms)^#ifdef NORMALIZED\n(?:(?!^#endif).)*?^INCLUDE_ASM\("[^"]*", %s\);.*?^#endif\n'
                  % re.escape(fn), text)
    if m:
        # the wrapper must be this function's own (no other #ifdef inside)
        if m.group(0).count("#ifdef NORMALIZED") == 1:
            return m.start(), m.end()
    m = re.search(r'(?m)^INCLUDE_ASM\("[^"]*", %s\);\n' % re.escape(fn), text)
    if m:
        return m.start(), m.end()
    m = re.search(r"(?m)^[A-Za-z_][^;{}()\n]*\b%s\s*\([^;{}]*\)\s*(?:[^;{}()]*;\s*)*\{" % re.escape(fn), text)
    if not m:
        return None
    i, depth = text.index("{", m.start()), 0
    while True:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    e = text.index("\n", i) + 1
    return m.start(), e


# Files whose rodata stays in the unit's asm rodata file (PsyQ library code is not
# touched, issue #5).
KEEP_ASM = ("psyq.c", "stag1000_libpress.c")


def apply(unit):
    """Insert INCLUDE_RODATA lines into src/<unit>/*.c for every item that is not a
    cc1 table. An item goes in front of the earliest function that owns it or any item
    after it in the same file (file-scope data comes before the functions that follow
    it), or after its owner when it follows the owner's own cc1 table. Items of
    KEEP_ASM files stay in the asm rodata file. Idempotent."""
    rows, probs = plan(unit)
    if any(r["how"] in ("orphan", "unknown-owner") for r in rows):
        sys.exit("cannot apply %s: %s" % (unit, [r for r in rows if r["how"] in ("orphan", "unknown-owner")]))
    rows = [r for r in rows if os.path.basename(r["file"]) not in KEEP_ASM]
    folder = "asm/USA/%s/rodata" % unit
    pre, post, seen = {}, {}, set()
    for k, r in enumerate(rows):
        if r["how"] == "cc1":
            seen.add(r["owner"])
            continue
        later = [x for x in rows[k:] if x["file"] == r["file"]]
        anchor = min(later, key=lambda x: x["owner_addr"])["owner"]
        if anchor == r["owner"] and r["owner"] in seen:
            post.setdefault(r["owner"], []).append(r)
        else:
            if anchor in seen:
                sys.exit("cannot place %s before %s: after its cc1 table" % (r["name"], anchor))
            pre.setdefault(anchor, []).append(r)
    files = {}
    for d in (pre, post):
        for o, rs in d.items():
            files.setdefault(rs[0]["file"], []).append(o)
    for f in files:
        t = open(f, encoding="latin-1").read()
        for o in sorted(set(files[f]), key=lambda o: -_def_span(t, o)[0] if _def_span(t, o) else 0):
            span = _def_span(t, o)
            if span is None:
                sys.exit("%s: definition of %s not found" % (f, o))
            s, e = span
            after = "".join('INCLUDE_RODATA("%s", %s);\n' % (folder, r["name"]) for r in post.get(o, [])
                            if 'INCLUDE_RODATA("%s", %s);' % (folder, r["name"]) not in t)
            before = "".join('INCLUDE_RODATA("%s", %s);\n' % (folder, r["name"]) for r in pre.get(o, [])
                             if 'INCLUDE_RODATA("%s", %s);' % (folder, r["name"]) not in t)
            t = t[:s] + before + t[s:e] + after + t[e:]
        open(f, "w", encoding="latin-1", newline="").write(t)
        print("%s: INCLUDE_RODATA for %d functions" % (f, len(set(files[f]))))


def keep_asm_text(unit):
    """The unit's rodata file reduced to the items of KEEP_ASM files (None if all moved)."""
    rows, _ = plan(unit)
    keep = [r["name"] for r in rows if r["file"] and os.path.basename(r["file"]) in KEEP_ASM]
    if not keep:
        return None
    t = open(rodata_file(unit), encoding="utf-8").read()
    head = t[:t.index("\n", t.index("/* Generated by spimdisasm")) + 1]
    body = "".join(text for name, _a, text in items_of(rodata_file(unit)) if name in keep)
    return head + re.sub(r"(?m)^\.align 3\n", "", body)


def main():
    unit = sys.argv[1]
    if "--split" in sys.argv:
        print("%d items split" % len(split(unit)))
        return
    if "--apply" in sys.argv:
        split(unit)
        apply(unit)
        return
    rows, probs = plan(unit)
    if "--json" in sys.argv:
        json.dump(dict(rows=rows, problems=probs), sys.stdout, indent=1)
        return
    for r in rows:
        print("%08X %-16s %-4s %-8s %s" % (r["addr"], r["name"], r["kind"], r["how"], r["owner"]))
    print("%d items, %d problems" % (len(rows), len(probs)))
    for p in probs:
        print("  " + p)


if __name__ == "__main__":
    main()
