.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_80063360

dlabel D_80063360
    /* 0 80063360 */ .asciz "MDEC_rest:bad option(%d)\n"
    /* 4D4445435F726573743A626164206F7074696F6E282564290A000000 */
.align 2
enddlabel D_80063360

.align 2
nonmatching D_8006337C

dlabel D_8006337C
    /* 1C 8006337C */ .asciz "MDEC_in_sync"
    /* 4D4445435F696E5F73796E6300000000 */
.align 2
enddlabel D_8006337C

.align 2
nonmatching D_8006338C

dlabel D_8006338C
    /* 2C 8006338C */ .asciz "MDEC_out_sync"
    /* 4D4445435F6F75745F73796E63000000 */
.align 2
enddlabel D_8006338C

.align 2
nonmatching D_8006339C

dlabel D_8006339C
    /* 3C 8006339C */ .asciz "%s timeout:\n"
    /* 25732074696D656F75743A0A00000000 */
.align 2
.align 2
    /* 4C 800633AC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8006339C
